### ISSUE TITLE
Logo Design: Nova

### ISSUE THREAD

**Issue by baranpirincal** [huisedenanhai/Nova#1]
Hello!

I'm a graphic designer and I like to support open source projects. I would like to design a logo for your project if you interested, I will be happy to work with you! :)

Best Regards

Baran Pirinçal

Graphic Designer

**Comment by martinwu42** [comment]
Hello, Baran! Our project is under early development yet, and we have a prototype for the logo. Your suggestions are welcomed!

As a word game, Nova is the pronunciation of its Chinese/Japanese name "能叶", literally "functioning leafs", where "能" stands for "机能" (function) or "能剧" (classical Japanese drama), and "叶" stands for "言叶" (speech) or "叶节点" (leaf nodes in the game's logic diagrams).

The SVG version is [here](https://send.firefox.com/download/28f224c677/#Ty65c2LpP3616EYDphwlSw). Apologize for our poor English:)

![Nova logo](https://user-images.githubusercontent.com/23053399/43139919-8bea491e-8f85-11e8-8db1-19c9454e3985.png)
